# Define the source file and output PDF
# TEXFILES=$(wildcard *.tex)
TARGET=fi-pdflatex.tex
TEXFILES=$(TARGET)
PDFS=$(TEXFILES:.tex=.pdf)
CLASS=fithesis4.cls

# The rule to generate the PDF
all: $(PDFS)

# Typeset twice in case there are logos, etc.
%.pdf: %.tex $(CLASS)
	pdflatex $<
	biber $(shell basename $< .tex) 
	pdflatex $<

open: clean $(TARGET:.tex=.pdf)
	open $(TARGET:.tex=.pdf)

# Clean auxiliary files generated by pdflatex
clean: clean_aux
	rm -f *.pdf

# Remove auxiliary files but keep the PDF
clean_aux:
	rm -f *.aux *.log *.toc *.out *.lof *.lot *.bbl *.blg *.idx *.ilg *.synctex.gz *.nav *.snm *.vrb *.bcf *.run.xml

.PHONY: all clean clean_aux

